//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteYonetimi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HAREKET
    {
        public TBL_HAREKET()
        {
            this.TBL_CEZALAR = new HashSet<TBL_CEZALAR>();
        }
    
        public byte ID { get; set; }
        public Nullable<int> Aidatİd { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<byte> PERSONEL { get; set; }
        public Nullable<System.DateTime> HesapKesim { get; set; }
        public Nullable<System.DateTime> SonOdeme { get; set; }
        public Nullable<bool> ISLEMDURUM { get; set; }
        public Nullable<System.DateTime> UYEGETIRTARIH { get; set; }
    
        public virtual TBL_Aidat TBL_Aidat { get; set; }
        public virtual ICollection<TBL_CEZALAR> TBL_CEZALAR { get; set; }
        public virtual TBL_UYELER TBL_UYELER { get; set; }
    }
}
