//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteYonetimi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Borc
    {
        public int ID { get; set; }
        public Nullable<int> DaireİD { get; set; }
        public Nullable<int> UyeİD { get; set; }
        public Nullable<int> AidatİD { get; set; }
        public string BorcAd { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBL_Aidat TBL_Aidat { get; set; }
        public virtual TBL_Daireler TBL_Daireler { get; set; }
        public virtual TBL_UYELER TBL_UYELER { get; set; }
    }
}
