//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteYonetimi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UYELER
    {
        public TBL_UYELER()
        {
            this.TBL_Daireler = new HashSet<TBL_Daireler>();
            this.TBL_HAREKET = new HashSet<TBL_HAREKET>();
            this.TBL_Borc = new HashSet<TBL_Borc>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string MAIL { get; set; }
        public string KULLANICIADI { get; set; }
        public string SIFRE { get; set; }
        public string FOTOGRAF { get; set; }
        public string TELEFON { get; set; }
        public string OKUL { get; set; }
        public string Role { get; set; }
    
        public virtual TBL_Aidat TBL_Aidat { get; set; }
        public virtual ICollection<TBL_Daireler> TBL_Daireler { get; set; }
        public virtual ICollection<TBL_HAREKET> TBL_HAREKET { get; set; }
        public virtual ICollection<TBL_Borc> TBL_Borc { get; set; }
    }
}
