//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteYonetimi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ILETISIM
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string MAIL { get; set; }
        public string TELEFON { get; set; }
        public string KONU { get; set; }
        public string MESAJ { get; set; }
    }
}
