//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteYonetimi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Gelir
    {
        public int İD { get; set; }
        public string GelirAd { get; set; }
        public Nullable<byte> Kategori { get; set; }
        public string GelirBilgi { get; set; }
        public Nullable<int> GelirTl { get; set; }
        public Nullable<int> ToplamGelir { get; set; }
    
        public virtual TBL_KATEGORI TBL_KATEGORI { get; set; }
        public virtual TBL_Gider TBL_Gider { get; set; }
    }
}
