//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteYonetimi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Daireler
    {
        public TBL_Daireler()
        {
            this.TBL_Aidat = new HashSet<TBL_Aidat>();
            this.TBL_Borc = new HashSet<TBL_Borc>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BlokNo { get; set; }
        public string BlokAd { get; set; }
        public Nullable<int> DaireNo { get; set; }
        public string DaireDurum { get; set; }
        public Nullable<int> DaireİD { get; set; }
        public Nullable<int> BorcİD { get; set; }
        public Nullable<int> UyeİD { get; set; }
    
        public virtual ICollection<TBL_Aidat> TBL_Aidat { get; set; }
        public virtual ICollection<TBL_Borc> TBL_Borc { get; set; }
        public virtual TBL_UYELER TBL_UYELER { get; set; }
    }
}
